//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorting_Program.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dayCanNhap
        {
            get
            {
                return ((string)(this["dayCanNhap"]));
            }
            set
            {
                this["dayCanNhap"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MauNenNode
        {
            get
            {
                return ((global::System.Drawing.Color)(this["MauNenNode"]));
            }
            set
            {
                this["MauNenNode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color MauNodeDaXetQua
        {
            get
            {
                return ((global::System.Drawing.Color)(this["MauNodeDaXetQua"]));
            }
            set
            {
                this["MauNodeDaXetQua"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color MauNodeDangXet
        {
            get
            {
                return ((global::System.Drawing.Color)(this["MauNodeDangXet"]));
            }
            set
            {
                this["MauNodeDangXet"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 13pt")]
        public global::System.Drawing.Font fontYTuongTextBox
        {
            get
            {
                return ((global::System.Drawing.Font)(this["fontYTuongTextBox"]));
            }
            set
            {
                this["fontYTuongTextBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri, 14pt")]
        public global::System.Drawing.Font fontCodeListBox
        {
            get
            {
                return ((global::System.Drawing.Font)(this["fontCodeListBox"]));
            }
            set
            {
                this["fontCodeListBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int KichCoNode
        {
            get
            {
                return ((int)(this["KichCoNode"]));
            }
            set
            {
                this["KichCoNode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int KhoanCachGiuaCacNode
        {
            get
            {
                return ((int)(this["KhoanCachGiuaCacNode"]));
            }
            set
            {
                this["KhoanCachGiuaCacNode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SoLuongPhanTuMacDinh
        {
            get
            {
                return ((int)(this["SoLuongPhanTuMacDinh"]));
            }
            set
            {
                this["SoLuongPhanTuMacDinh"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MauNenForm
        {
            get
            {
                return ((bool)(this["MauNenForm"]));
            }
            set
            {
                this["MauNenForm"] = value;
            }
        }
    }
}
